// Code generated by reactGen. DO NOT EDIT.

package react

// DelProps defines the properties for the <Del> element.
type DelProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	Cite                    string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	DateTime string
	ID       string
	Key      string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (d *DelProps) assign(_v *_DelProps) {

	_v.AriaExpanded = d.AriaExpanded

	_v.AriaHasPopup = d.AriaHasPopup

	_v.AriaLabelledBy = d.AriaLabelledBy

	_v.Cite = d.Cite

	_v.ClassName = d.ClassName

	_v.DangerouslySetInnerHTML = d.DangerouslySetInnerHTML

	if d.DataSet != nil {
		for dk, dv := range d.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	_v.DateTime = d.DateTime

	if d.ID != "" {
		_v.ID = d.ID
	}

	if d.Key != "" {
		_v.Key = d.Key
	}

	if d.OnChange != nil {
		_v.o.Set("onChange", d.OnChange.OnChange)
	}

	if d.OnClick != nil {
		_v.o.Set("onClick", d.OnClick.OnClick)
	}

	if d.Ref != nil {
		_v.o.Set("ref", d.Ref.Ref)
	}

	_v.Role = d.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = d.Style.hack()

}
