// Code generated by reactGen. DO NOT EDIT.

package react

// VarProps defines the properties for the <Var> element.
type VarProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (v *VarProps) assign(_v *_VarProps) {

	_v.AriaExpanded = v.AriaExpanded

	_v.AriaHasPopup = v.AriaHasPopup

	_v.AriaLabelledBy = v.AriaLabelledBy

	_v.ClassName = v.ClassName

	_v.DangerouslySetInnerHTML = v.DangerouslySetInnerHTML

	if v.DataSet != nil {
		for dk, dv := range v.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	if v.ID != "" {
		_v.ID = v.ID
	}

	if v.Key != "" {
		_v.Key = v.Key
	}

	if v.OnChange != nil {
		_v.o.Set("onChange", v.OnChange.OnChange)
	}

	if v.OnClick != nil {
		_v.o.Set("onClick", v.OnClick.OnClick)
	}

	if v.Ref != nil {
		_v.o.Set("ref", v.Ref.Ref)
	}

	_v.Role = v.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = v.Style.hack()

}
