// Code generated by reactGen. DO NOT EDIT.

package react

// ScriptProps defines the properties for the <Script> element.
type ScriptProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	Async                   string
	ClassName               string
	CrossOrigin             string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	Defer     string
	ID        string
	Integrity string
	Key       string
	NoModule  string
	Nonce     string

	OnChange
	OnClick

	Ref
	Role  string
	Src   string
	Style *CSS
	Text  string
	Type  string
}

func (s *ScriptProps) assign(_v *_ScriptProps) {

	_v.AriaExpanded = s.AriaExpanded

	_v.AriaHasPopup = s.AriaHasPopup

	_v.AriaLabelledBy = s.AriaLabelledBy

	_v.Async = s.Async

	_v.ClassName = s.ClassName

	_v.CrossOrigin = s.CrossOrigin

	_v.DangerouslySetInnerHTML = s.DangerouslySetInnerHTML

	if s.DataSet != nil {
		for dk, dv := range s.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	_v.Defer = s.Defer

	if s.ID != "" {
		_v.ID = s.ID
	}

	_v.Integrity = s.Integrity

	if s.Key != "" {
		_v.Key = s.Key
	}

	_v.NoModule = s.NoModule

	_v.Nonce = s.Nonce

	if s.OnChange != nil {
		_v.o.Set("onChange", s.OnChange.OnChange)
	}

	if s.OnClick != nil {
		_v.o.Set("onClick", s.OnClick.OnClick)
	}

	if s.Ref != nil {
		_v.o.Set("ref", s.Ref.Ref)
	}

	_v.Role = s.Role

	_v.Src = s.Src

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = s.Style.hack()

	_v.Text = s.Text

	_v.Type = s.Type

}
