// Code generated by reactGen. DO NOT EDIT.

package react

// MeterProps defines the properties for the <Meter> element.
type MeterProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	Form string
	High float64
	ID   string
	Key  string
	Low  float64
	Max  float64
	Min  float64

	OnChange
	OnClick

	Optimum float64
	Ref
	Role  string
	Style *CSS
	Value float64
}

func (m *MeterProps) assign(_v *_MeterProps) {

	_v.AriaExpanded = m.AriaExpanded

	_v.AriaHasPopup = m.AriaHasPopup

	_v.AriaLabelledBy = m.AriaLabelledBy

	_v.ClassName = m.ClassName

	_v.DangerouslySetInnerHTML = m.DangerouslySetInnerHTML

	if m.DataSet != nil {
		for dk, dv := range m.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	_v.Form = m.Form

	_v.High = m.High

	if m.ID != "" {
		_v.ID = m.ID
	}

	if m.Key != "" {
		_v.Key = m.Key
	}

	_v.Low = m.Low

	_v.Max = m.Max

	_v.Min = m.Min

	if m.OnChange != nil {
		_v.o.Set("onChange", m.OnChange.OnChange)
	}

	if m.OnClick != nil {
		_v.o.Set("onClick", m.OnClick.OnClick)
	}

	_v.Optimum = m.Optimum

	if m.Ref != nil {
		_v.o.Set("ref", m.Ref.Ref)
	}

	_v.Role = m.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = m.Style.hack()

	_v.Value = m.Value

}
