// Code generated by reactGen. DO NOT EDIT.

package react

// EmProps defines the properties for the <Em> element.
type EmProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (e *EmProps) assign(_v *_EmProps) {

	_v.AriaExpanded = e.AriaExpanded

	_v.AriaHasPopup = e.AriaHasPopup

	_v.AriaLabelledBy = e.AriaLabelledBy

	_v.ClassName = e.ClassName

	_v.DangerouslySetInnerHTML = e.DangerouslySetInnerHTML

	if e.DataSet != nil {
		for dk, dv := range e.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	if e.ID != "" {
		_v.ID = e.ID
	}

	if e.Key != "" {
		_v.Key = e.Key
	}

	if e.OnChange != nil {
		_v.o.Set("onChange", e.OnChange.OnChange)
	}

	if e.OnClick != nil {
		_v.o.Set("onClick", e.OnClick.OnClick)
	}

	if e.Ref != nil {
		_v.o.Set("ref", e.Ref.Ref)
	}

	_v.Role = e.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = e.Style.hack()

}
