// Code generated by reactGen. DO NOT EDIT.

package react

// AreaProps defines the properties for the <Area> element.
type AreaProps struct {
	Alt                     string
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	ClassName               string
	Coords                  string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	Download string
	Href     string
	HrefLang string
	ID       string
	Key      string
	Media    string

	OnChange
	OnClick

	Ref
	ReferrerPolicy string
	Rel            string
	Role           string
	Shape          string
	Style          *CSS
	Target         string
}

func (a *AreaProps) assign(_v *_AreaProps) {

	_v.Alt = a.Alt

	_v.AriaExpanded = a.AriaExpanded

	_v.AriaHasPopup = a.AriaHasPopup

	_v.AriaLabelledBy = a.AriaLabelledBy

	_v.ClassName = a.ClassName

	_v.Coords = a.Coords

	_v.DangerouslySetInnerHTML = a.DangerouslySetInnerHTML

	if a.DataSet != nil {
		for dk, dv := range a.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	_v.Download = a.Download

	_v.Href = a.Href

	_v.HrefLang = a.HrefLang

	if a.ID != "" {
		_v.ID = a.ID
	}

	if a.Key != "" {
		_v.Key = a.Key
	}

	_v.Media = a.Media

	if a.OnChange != nil {
		_v.o.Set("onChange", a.OnChange.OnChange)
	}

	if a.OnClick != nil {
		_v.o.Set("onClick", a.OnClick.OnClick)
	}

	if a.Ref != nil {
		_v.o.Set("ref", a.Ref.Ref)
	}

	_v.ReferrerPolicy = a.ReferrerPolicy

	_v.Rel = a.Rel

	_v.Role = a.Role

	_v.Shape = a.Shape

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = a.Style.hack()

	_v.Target = a.Target

}
