// Code generated by reactGen. DO NOT EDIT.

package react

// WbrProps defines the properties for the <Wbr> element.
type WbrProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (w *WbrProps) assign(_v *_WbrProps) {

	_v.AriaExpanded = w.AriaExpanded

	_v.AriaHasPopup = w.AriaHasPopup

	_v.AriaLabelledBy = w.AriaLabelledBy

	_v.ClassName = w.ClassName

	_v.DangerouslySetInnerHTML = w.DangerouslySetInnerHTML

	if w.DataSet != nil {
		for dk, dv := range w.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	if w.ID != "" {
		_v.ID = w.ID
	}

	if w.Key != "" {
		_v.Key = w.Key
	}

	if w.OnChange != nil {
		_v.o.Set("onChange", w.OnChange.OnChange)
	}

	if w.OnClick != nil {
		_v.o.Set("onClick", w.OnClick.OnClick)
	}

	if w.Ref != nil {
		_v.o.Set("ref", w.Ref.Ref)
	}

	_v.Role = w.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = w.Style.hack()

}
