// Code generated by reactGen. DO NOT EDIT.

package react

// KbdProps defines the properties for the <Kbd> element.
type KbdProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (k *KbdProps) assign(_v *_KbdProps) {

	_v.AriaExpanded = k.AriaExpanded

	_v.AriaHasPopup = k.AriaHasPopup

	_v.AriaLabelledBy = k.AriaLabelledBy

	_v.ClassName = k.ClassName

	_v.DangerouslySetInnerHTML = k.DangerouslySetInnerHTML

	if k.DataSet != nil {
		for dk, dv := range k.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	if k.ID != "" {
		_v.ID = k.ID
	}

	if k.Key != "" {
		_v.Key = k.Key
	}

	if k.OnChange != nil {
		_v.o.Set("onChange", k.OnChange.OnChange)
	}

	if k.OnClick != nil {
		_v.o.Set("onClick", k.OnClick.OnClick)
	}

	if k.Ref != nil {
		_v.o.Set("ref", k.Ref.Ref)
	}

	_v.Role = k.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = k.Style.hack()

}
