// Code generated by reactGen. DO NOT EDIT.

package react

// MainProps defines the properties for the <Main> element.
type MainProps struct {
	AriaExpanded            bool
	AriaHasPopup            bool
	AriaLabelledBy          string
	ClassName               string
	DangerouslySetInnerHTML *DangerousInnerHTML
	DataSet
	ID  string
	Key string

	OnChange
	OnClick

	Ref
	Role  string
	Style *CSS
}

func (m *MainProps) assign(_v *_MainProps) {

	_v.AriaExpanded = m.AriaExpanded

	_v.AriaHasPopup = m.AriaHasPopup

	_v.AriaLabelledBy = m.AriaLabelledBy

	_v.ClassName = m.ClassName

	_v.DangerouslySetInnerHTML = m.DangerouslySetInnerHTML

	if m.DataSet != nil {
		for dk, dv := range m.DataSet {
			_v.o.Set("data-"+dk, dv)
		}
	}

	if m.ID != "" {
		_v.ID = m.ID
	}

	if m.Key != "" {
		_v.Key = m.Key
	}

	if m.OnChange != nil {
		_v.o.Set("onChange", m.OnChange.OnChange)
	}

	if m.OnClick != nil {
		_v.o.Set("onClick", m.OnClick.OnClick)
	}

	if m.Ref != nil {
		_v.o.Set("ref", m.Ref.Ref)
	}

	_v.Role = m.Role

	// TODO: until we have a resolution on
	// https://github.com/gopherjs/gopherjs/issues/236
	_v.Style = m.Style.hack()

}
